# -*- coding: utf-8 -*-
"""hw_1.3.4 Цикл while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vA1-3dYbLaPUuCz5AeEaNvNOorfBKqD3

#Домашнє завдання до теми "Цикл while"

1. **Лічильник до заданого числа.**
   Завдання:
     - Створіть цикл `while`, щоб він лічив від 1 до заданого числа в змінній `limit`.
     - Виведіть кожне число, яке проходить лічильник, на екран.
     - В кінці виведіть повідомлення "Кінець розрахунку!".
"""

limit = 9  # Задане число

counter = 1
while counter <= limit:
    print(counter)
    counter += 1
print("Кінець розрахунку!")

"""2. **Пошук першого парного числа.** Завдання:
     - Створіть цикл `while`, щоб знайти перше парне число після заданого числа `start`.
     - Знайдіть та виведіть перше парне число.

"""

start = 7  # Задане число

current_number = start + 1
while True:
    if current_number % 2 == 0:
        print(current_number)
        break
    current_number += 1

"""
3. **Обчислення факторіалу.**   
  Факторіал числа - це добуток всіх натуральних чисел від 1 до цього числа включно. Наприклад, факторіал числа 5 (позначається як 5!) дорівнює `1 * 2 * 3 * 4 * 5 = 120`.

  Завдання:  
      - Обчисліть факторіал заданого числа, використовуючи цикл `while`.  
      - Задайте деяке число для обчислення факторіалу у змінній `num`.  
      - Виведіть обчислений факторіал на екран.  
"""

num = 5
factorial = 1
current_number = 1
while current_number <= num:
    factorial *= current_number
    current_number += 1
print(factorial)